# This is a dummy workflow used to test and demonstrate workflow workings.
name: Dummy Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: build-output-dir
      shell: bash
      run: |
        echo "build-output-dir=$HOME/builds" >> $GITHUB_ENV

    - name: Configure CMake
      id: cmake-configure
      run: |
        echo "Build output directory: ${{ steps.strings.output.build-output-dir }}"
        cmake -B ${{ steps.strings.output.build-output-dir }} -S . -G Ninja -DCMAKE_BUILD_TYPE=Release