# This is a dummy workflow used to test and demonstrate workflow workings.
name: Dummy Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        if [[ ${{ matrix.os }} == 'windows-latest' ]]; then
          echo "build-output-dir=C:\\builds" >> $GITHUB_OUTPUT
        else
          echo "build-output-dir=$HOME/builds" >> $GITHUB_OUTPUT
        fi

    - name: Configure CMake
      id: cmake-configure
      run: |
        echo "Build output directory: ${{ steps.strings.outputs.build-output-dir }}"
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -S . -G Ninja -DCMAKE_BUILD_TYPE=Release