# This is a dummy workflow used to test and demonstrate workflow workings.
name: Dummy Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings for Windows Runner
      id: set-strings-windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $BuildOutputDir = "$HOME\builds"
        Write-Output ::set-output name=GITHUB_ENV::"build-output-dir=$BuildOutputDir"
        Write-Output $GITHUB_ENV

    - name: Set reusable strings for Ubuntu Runner
      id: set-strings-ubuntu
      if: runner.os == 'Linux'
      run: |
        BuildOutputDir="$HOME/builds"
        echo "build-output-dir=$BuildOutputDir" >> $GITHUB_ENV
        echo $GITHUB_ENV
