# This is a dummy workflow used to test and demonstrate workflow workings.
name: Dummy Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings for Windows Runner
      id: build-output-dir
      shell: bash
      run: |
        $BuildOutputDir="$HOME/builds"
        echo "build-output-dir=$BuildOutputDir" >> $GITHUB_ENV
        echo ${{ steps.strings.outputs.build-output-dir }}
